# The URL the site will be built for
base_url = "https://hugodaniel.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

ignored_content = ["*/shader-canvas/*"]

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

light_theme = "solarized-light"
dark_theme = "solarized-dark"

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
extra_themes = []


[extra]
# Put all your custom variables here
